args:
  stage: 0 
  stop_stage: 1
  nbest: 10
  withLM: True
  dataset: librispeech

train:
  start_epoch: 0
  epoch: 10
  train_batch: 32
  valid_batch: 32
  accumgrad: 8
  print_loss: 2000
  lr: 1e-6
  data_type: single
  sep_token: None
  from_pretrain: True

recog:
  batch: 32
