args:
  stage: 0 
  stop_stage: 1
  nbest: 10
  withLM: False
  dataset: aishell

train:
  start_epoch: 0
  epoch: 10
  train_batch: 64
  valid_batch: 64
  accumgrad: 4
  print_loss: 2000
  lr: 1e-5
  data_type: single
  sep_token: None
  from_pretrain: True

recog:
  batch: 1
