args:
  stage: 0 
  stop_stage: 1
  nbest: 10
  withLM: True
  dataset: tedlium2

train:
  start_epoch: 0
  epoch: 10
  train_batch: 128
  valid_batch: 64
  accumgrad: 1
  print_loss: 2000
  lr: 1e-5
  data_type: single

recog:
  batch: 64
