args:
  stage: 0 
  stop_stage: 1
  nbest: 4
  withLM: False
  dataset: aishell

train:
  start_epoch: 0
  epoch: 10
  train_batch: 32
  valid_batch: 32
  accumgrad: 8
  print_loss: 2000
  lr: 1e-5
  data_type: concat
  sep_token: '#'
  from_pretrain: True

recog:
  batch: 1