args:
  stage: 0 
  stop_stage: 1
  nbest: 4
  withLM: True
  dataset: librispeech

train:
  start_epoch: 0
  epoch: 10
  train_batch: 8
  valid_batch: 8
  accumgrad: 32
  print_loss: 2000
  lr: 1e-6
  data_type: concat
  sep_token: '#'
  from_pretrain: True

recog:
  batch: 16