args:
  stage: 2
  stop_stage: 2
  withLM: True
  dataset: aishell2

train: 
  start_epoch: 0
  epoch: 10
  train_batch: 32
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  nbest: 2
  mode: concat
  lr: 1e-5
  model_name: bart
  checkpoint: # /work/jason90255/rescoring/checkpoint/nBestTransformer/align/bart/checkpoint_train_10.pt

recog:
  batch: 1
  max_len: 50