stage: 0
stop_stage: 100
nbest: 10  # max: 50

train: 
  epoch: 10
  train_batch: 24
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  lr: 1e-5
  use_spike: True
  use_res: False
  train_json: /tmp/data/aishell_train/bert_token/audio_data.json
  valid_json: /tmp/data/aishell_dev/bert_token/audio_data.json
  dev_json: /tmp/data/aishell_dev/bert_token/audio_data_no_align.json
  test_json: /tmp/data/aishell_test/bert_token/audio_data_no_align.json

recog:
  batch: 1