stage: 0
stop_stage: 100
nbest: 10  # max: 50

train: 
  epoch: 1
  train_batch: 16
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  lr: 1e-5
  use_spike: True
  use_res: False
  train_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_train/50_best/bert_token/audio_data.json
  valid_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_dev/50_best/bert_token/audio_data.json
  dev_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_dev/50_best/bert_token/audio_data_no_align.json
  test_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_test/50_best/bert_token/audio_data_no_align.json
  train_recog_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_train/50_best/bert_token/audio_data_no_align.json

recog:
  batch: 1