args:
  stage: 0
  stop_stage: 100
  nbest: 50
  withLM: True
  dataset: aishell

train:
  epoch: 10
  train_batch: 4
  valid_batch: 1
  accumgrad: 64
  print_loss: 200
  lr: 5e-4
  mode: scoring
  train_json: ./data/aishell/train/token/token_withLM_50best.json
  dev_json: ./data/aishell/dev/token/token_withLM_50best.json
  test_json: ./data/aishell/test/token/token_withLM_50best.json

recog:
  batch: 1