stage: 1

train: 
  epoch: 20
  train_batch: 256
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  mode: align
  lr: 1e-5
  train_json: /work/jason90255/rescoring/data/aishell_train/bart_token/align_token.json
  dev_json: /work/jason90255/rescoring/data/aishell_dev/bart_token/align_token.json
  test_json: /work/jason90255/rescoring/data/aishell_test/bart_token/align_token.json
  model_name: bart
  checkpoint: /work/jason90255/rescoring/checkpoint/nBestTransformer/align/bart/checkpoint_train_10.pt

recog:
  batch: 1
  max_len: 50