stage: 3
stop_stage: 100
nbest: 50  # max: 50
withLM: False
dataset: aishell

adapt:
  epoch: 1
  accum_grad: 1
  print_loss: 200
  mode: random
  # random mode batch
  train_batch: 256
  # sequence mode batch
  mlm_batch: 16
  lr: 1e-5

train: 
  epoch: 10
  train_batch: 8
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  mode: MWED
  lr: 1e-5
  train_json: ./data/aishell/train/token/token_noLM_50best.json
  dev_json: ./data/aishell/dev/token/token_noLM_50best.json
  test_json: ./data/aishell/test/token/token_noLM_50best.json

recog:
  batch: 1
  find_weight: True