stage: 0
adapt:
  epoch: 1
  accum_grad: 1
  print_loss: 200
  mode: sequence
  # random mode batch
  train_batch: 256
  # sequence mode batch
  mlm_batch: 32
  lr: 1e-5

train: 
  epoch: 10
  train_batch: 10
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  mode: MWER
  lr: 1e-5
  train_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_train/10_best/bart_token/token.json
  dev_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_dev/10_best/bart_token/token.json
  test_json: /mnt/nas3/Alfred/RescoreBert/data/aishell_test/10_best/bart_token/token.json

recog:
  batch: 1
  find_weight: True