args:
  stage: 0
  stop_stage: 100
  nbest: 10
  withLM: False
  dataset: aishell
  MLM: False
  jp_split: False

train:
  epoch: 10
  train_batch: 256
  valid_batch: 256
  accumgrad: 1
  print_loss: 200
  lr: 1e-5
  mode: scoring

recog:
  batch: 256