args:
  stage: 0
  stop_stage: 100
  nbest: 50
  withLM: True
  dataset: librispeech
  MLM: False
  jp_split: False

train:
  epoch: 30
  train_batch: 64
  valid_batch: 64
  accumgrad: 2
  print_loss: 200
  lr: 1e-5
  mode: scoring

recog:
  batch: 128