args:
  stage: 0
  stop_stage: 100
  nbest: 50
  withLM: True
  dataset: csj
  MLM: True
  jp_split: True

train:
  epoch: 30
  train_batch: 128
  valid_batch: 64
  accumgrad: 1
  print_loss: 200
  lr: 1e-5
  mode: scoring

recog:
  batch: 64
