args:
  nbest: 50 # max: 50
  withLM: True
  dataset: aishell

train:
  epoch: 10
  batch_size: 256
  accumgrad: 1
  print_loss: 5000
  lr: 1e-8
  freeze_epoch: -1
  hard_label: True
  warmup_step: 10000

recog:
  batch: 1
  find_weight: True 