args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell

train:
  epoch: 10
  batch_size: 256
  accumgrad: 1
  print_loss: 5000
  lr: 1e-6
  freeze_epoch: -1
  hard_label: True
  margin_value: 0.1
  converge: 0.1
  margin_mode: 
  contrast_weight: 1.0
  warmup_ratio: 0.1
  loss_type: Entropy
  useTopOnly: False
  compareWith: SELF-LSTM # SELF, POOL , SELF-CSE, SELF-QE, SELF_LSTM or REF, REF-HARD
  noCLS: True
  noSEP: True
  layer_op:
  # lastInit_n, n = number of layers
  temperature: 0.05
  force_Ref: True
  reduction: sum
  MWER: 

recog:
  batch: 1
  find_weight: True