args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell

train:
  epoch: 10
  batch_size: 1024
  accumgrad: 1
  print_loss: 5000
  lr: 1e-7
  freeze_epoch: -1
  hard_label: True
  warmup_step: 10000
  margin: 0.1

recog:
  batch: 1
  find_weight: True 