args:
  stage: 0
  stop_stage: 100
  nbest: 50
  withLM: False
  dataset: aishell
  MLM: True

train:
  epoch: 10
  train_batch: 64
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  lr: 1e-5
  mode: scoring

recog:
  batch_size: 128
  lower_bound: 0.0
  upper_bound: 1.0
  length_norm: False