args:
  stage: 0
  stop_stage: 100
  nbest: 10
  withLM: True
  dataset: tedlium2
  MLM: True
  jp_split: False # if True, training data will be split by char
  for_train: False

train:
  epoch: 10
  train_batch: 128
  valid_batch: 128
  accumgrad: 2
  print_loss: 200
  lr: 1e-5
  mode: scoring

recog:
  batch_size: 128
  lower_bound: 0.0
  upper_bound: 1.0
  length_norm: False