args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell

train:
  epoch: 10
  freeze_gpt_epoch: -1
  batch_size: 128
  accumgrad: 1
  print_loss: 500
  lr: 1e-5
  lstm_embedding: 1024

recog:
  batch: 32
  find_weight: True 