args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell
  seed: 42

train:
  epoch: 10
  AttLayer: 1
  batch_size: 100
  valid_batch: 1
  accumgrad: 1
  print_loss: 5000
  lr: 1e-7
  maxlr: 1e-7
  freeze_epoch: -1
  fuseType: none  # lstm , attn, query or None
  lstm_embedding: 1024
  useNBestCross: False
  trainAttendWeight: False
  addRes: True
  hardLabel: True
  logSoftmax: False
  lossType: 'Entropy'
  sortByLen: True
  concatCLS: False
  concatMaskAfter: True # if True [CLS] tokens [SEP] [MASK]  else [CLS] tokens [MASK] [SEP]
  dropout: 0.3
  weightByGrad: False
  train_cls_first: False
  sepTask: True
  2ndTask: "GT" # "GT" or "WER"
  scoreByRank: False
  noCLS: False
  noSEP: False

recog:
  batch: 1
  find_weight: True