args:
  nbest: 10 # max: 50
  withLM: False
  dataset: csj
  seed: 42

train:
  epoch: 10
  AttLayer: 
  batch_size: 128
  valid_batch: 1
  accumgrad: 2
  print_loss: 5000
  lr: 1e-5
  freeze_epoch: -1
  fuseType: lstm # lstm , attn or None
  lstm_embedding: 1024
  hardLabel: True
  logSoftmax: False
  lossType: Entropy
  sortByLen: True
  concatCLS: False
  dropout: 0.3
  noCLS: False
  noSEP: False
  warmup_ratio: 0.01

recog:
  batch: 1
  find_weight: True