args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell
  seed: 42

train:
  epoch: 10
  AttLayer: 1
  batch_size: 256
  valid_batch: 1
  accumgrad: 1
  print_loss: 5000
  lr: 1e-6
  freeze_epoch: -1
  fuseType: lstm # lstm , attn or None
  lstm_embedding: 1024
  hardLabel: True
  logSoftmax: False
  lossType: Entropy
  sortByLen: True
  concatCLS: False
  dropout: 0.3
  noCLS: False
  noSEP: False
  warmup_ratio: 0.1

recog:
  batch: 1
  find_weight: True