args:
  nbest: 50 # max: 50
  withLM: False
  dataset: aishell
  seed: 42

train:
  epoch: 10
  AttLayer: 1
  batch_size: 256
  valid_batch: 1
  accumgrad: 1
  print_loss: 5000
  lr: 1e-7
  maxlr: 1e-7
  freeze_epoch: -1
  fuseType: none  # lstm , attn or None
  lstm_embedding: 1024
  useNBestCross: True
  trainAttendWeight: False
  hardLabel: True
  logSoftmax: False
  lossType: CE
  sortByLen: True
  concatCLS: False
  dropout: 0.3
  weightByGrad: False
  noCLS: False
  noSEP: False
  warmup_ratio: 0.1

recog:
  batch: 1
  find_weight: True