args:
  stage: 4
  stop_stage: 100
  nbest: 50 # max: 50
  withLM: True
  dataset: aishell2
  free_memory: True
  sentence_per_process: 40 # Activated when free_memory = true

adapt:
  epoch: 1
  accum_grad: 1
  print_loss: 200
  mode: random
  # random mode batch
  train_batch: 128
  # sequence mode batch
  mlm_batch: 16
  lr: 1e-5

train:
  epoch: 10
  train_batch: 4
  valid_batch: 1
  accumgrad: 1
  print_loss: 200
  mode: MD
  lr: 5e-6

recog:
  batch: 1
  find_weight: True
