args:
  dataset: tedlium2
  withLM: False
  add_additional_feat: False
  add_am_lm_score: True
train:
  train_batch: 256
  valid_batch: 32
  train_epoch: 10
  hidden_dim: 100
  output_dim: 103
  accum_grad: 1
  lr: 1e-4
  logging_loss: 200

recog:
  recog_batch: 1