args:
  nbest: 10 # max: 50
  withLM: False
  dataset: csj

train:
  epoch: 10
  train_batch: 128
  accumgrad: 2
  print_loss: 1000
  lr: 1e-6
  reduction: sum
  loss_type: Entropy
  optim: adamW
  use_WER: False
  use_Norm: False
  use_rank: False
  hard_label: True

recog:
  batch: 256
  for_train: False
  test_speed: True
  find_weight: True 