args:
  nBest: 5
  withLM: False
  model_name: alsem
  dataset: aishell2

train: 
  epoch: 4
  train_batch: 256
  valid_batch: 256
  accum_grads: 1
  print_loss: 5000
  lr: 1e-5
  ctc_weight: 0.3

recog:
  batch: 64
  find_weight: True