args:
  nBest: 10
  withLM: True
  model_name: alsem
  dataset: aishell

train: 
  epoch: 4
  train_batch: 256
  valid_batch: 256
  accum_grads: 1
  print_loss: 5000
  lr: 1e-5
  ctc_weight: {aishell: 0.7,
  aishell2: 0.5,
  librispeech: 0.5,
  csj: 0.3,
  tedlium2: 0.3
}
  

recog:
  batch: 1
  find_weight: True