args:
  nBest: 20
  withLM: True
  model_name: alsem
  dataset: tedlium2

train: 
  epoch: 4
  train_batch: 64
  valid_batch: 64
  accum_grads: 4
  print_loss: 5000
  lr: 1e-5
  ctc_weight: {aishell: 0.7,
  aishell2: 0.5,
  librispeech: 0.5,
  csj: 0.3,
  tedlium2: 0.3
}
  

recog:
  batch: 16
  find_weight: True