args:
  stage: 0
  stop_stage: 0
  nbest: 5 # max: 50
  withLM: True
  model_name: sem
  dataset: aishell

train:
  epoch: 4
  train_batch: 256
  valid_batch: 256
  accumgrad: 1
  print_loss: 200
  lr: 1e-6

recog:
  batch: 16
  find_weight: True
