args:
  stage: 0
  stop_stage: 0
  nbest: 20 # max: 50
  withLM: False
  model_name: sem
  dataset: csj

train:
  epoch: 4
  train_batch: 64
  valid_batch: 64
  accumgrad: 4
  print_loss: 5000
  lr: 1e-6

recog:
  batch: 16
  find_weight: True
