args:
  stage: 0
  stop_stage: 0
  nbest: 20 # max: 50
  withLM: True
  model_name: sem
  dataset: tedlium2

train:
  epoch: 4
  train_batch: 32
  valid_batch: 32
  accumgrad: 1
  print_loss: 200
  lr: 1e-5

recog:
  batch: 32
  find_weight: True
